CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email              VARCHAR(255)                            NOT NULL,
    password           VARCHAR(255)                            NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    avatar_url         VARCHAR(255),
    role               VARCHAR(255)                            NOT NULL,
    is_email_verified  BOOLEAN                                 NOT NULL,
    reset_token        VARCHAR(255),
    reset_token_expiry TIMESTAMP WITHOUT TIME ZONE,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);